#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define CG_I2C_MLX_FREQ_HZ 400000U
#define CG_I2C_ENV_FREQ_HZ 400000U
#define CG_I2C_TIMEOUT_MS 100U

#define CG_PMS_UART_BAUD_RATE 9600U
#define CG_PMS_UART_RX_BUFFER_SIZE 256U
#define CG_PMS_FRAME_LENGTH 32U
#define CG_PMS_FRAME_PAYLOAD_LENGTH 28U
#define CG_PMS_HEADER_1 0x42U
#define CG_PMS_HEADER_2 0x4DU
#define CG_PMS_WAKEUP_DISCARD_MS 30000U

#define CG_MLX90640_WIDTH 32U
#define CG_MLX90640_HEIGHT 24U
#define CG_MLX90640_PIXEL_COUNT (CG_MLX90640_WIDTH * CG_MLX90640_HEIGHT)
#define CG_MLX90640_EEPROM_START 0x2400U
#define CG_MLX90640_EEPROM_WORDS 832U
#define CG_MLX90640_FRAME_START 0x0400U
#define CG_MLX90640_FRAME_WORDS 834U
#define CG_MLX90640_DEFAULT_PERIOD_MS 500U
#define CG_MLX90640_VALID_MIN_TEMP_C (-40.0f)
#define CG_MLX90640_VALID_MAX_TEMP_C 300.0f

#define CG_MLX90640_TEST_VERSION "V1"
#define CG_THERMAL_UART_BAUD_RATE 115200U
#define CG_THERMAL_UART_TX_BUFFER_SIZE 4096U
#define CG_THERMAL_UART_RX_BUFFER_SIZE 256U

#define CG_OCCUPANCY_BACKGROUND_INIT_FRAMES 45U
#define CG_OCCUPANCY_BACKGROUND_PERCENT 0.70f
#define CG_OCCUPANCY_BETA 0.30f
#define CG_OCCUPANCY_SMOOTH_ALPHA CG_OCCUPANCY_BETA
#define CG_OCCUPANCY_ALPHA 0.005f
#define CG_OCCUPANCY_INTERFERENCE_MIN_DELTA 0.8f
#define CG_OCCUPANCY_INTERFERENCE_MAX_DELTA 2.5f
#define CG_OCCUPANCY_HUMAN_UPPER_TEMP_C 36.0f
#define CG_OCCUPANCY_PEAK_DELTA 1.2f
#define CG_OCCUPANCY_OUTLIER_COUNT_LIMIT 3U
#define CG_OCCUPANCY_MIN_SUPPORT_PIXELS 4U
#define CG_OCCUPANCY_MAX_OUTLIER_REMOVE_ITER 3U
#define CG_OCCUPANCY_HUMAN_THRESHOLD_BETA 0.37f
#define CG_OCCUPANCY_MIN_CANDIDATE_COUNT 6U
#define CG_OCCUPANCY_MIN_REGION_AREA 4U
#define CG_OCCUPANCY_MIN_COMPONENT_MAX_DELTA 0.5f
#define CG_OCCUPANCY_OCCUPIED_THRESHOLD 0.03f
#define CG_OCCUPANCY_SUSPECTED_THRESHOLD 0.015f
#define CG_OCCUPANCY_OCCUPIED_CONFIRM_FRAMES 5U
#define CG_OCCUPANCY_POSSIBLE_CONFIRM_FRAMES 3U
#define CG_OCCUPANCY_EMPTY_POSSIBLE_FRAMES 10U
#define CG_OCCUPANCY_EMPTY_CONFIRM_FRAMES 20U

#define CG_SCD41_DEFAULT_PERIOD_MS 5000U
#define CG_SHT35_DEFAULT_PERIOD_MS 2000U

#define CG_BEAM_DEBOUNCE_US 3000U
#define CG_BEAM_EVENT_QUEUE_LENGTH 16U

#define CG_HUB75_WIDTH 64U
#define CG_HUB75_HEIGHT 32U
#define CG_HUB75_DEFAULT_BRIGHTNESS 64U

#ifdef __cplusplus
}
#endif
