#pragma once

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/uart.h"

#ifdef __cplusplus
extern "C" {
#endif

#define CG_I2C_MLX_PORT I2C_NUM_0
#define CG_I2C_ENV_PORT I2C_NUM_1
#define CG_UART_PMS_PORT UART_NUM_1
#define CG_UART_LOG_PORT UART_NUM_0

#define CG_PIN_MLX_SDA GPIO_NUM_39
#define CG_PIN_MLX_SCL GPIO_NUM_40

#define CG_PIN_ENV_SDA GPIO_NUM_41
#define CG_PIN_ENV_SCL GPIO_NUM_42

#define CG_PIN_PMS_SET GPIO_NUM_14
#define CG_PIN_PMS_RX_FROM_SENSOR GPIO_NUM_21
#define CG_PIN_PMS_TX_TO_SENSOR GPIO_NUM_47
#define CG_PIN_PMS_RESET GPIO_NUM_48

#define CG_PIN_BEAM_1 GPIO_NUM_1
#define CG_PIN_BEAM_2 GPIO_NUM_2

#define CG_PIN_HUB75_R1 GPIO_NUM_4
#define CG_PIN_HUB75_G1 GPIO_NUM_5
#define CG_PIN_HUB75_B1 GPIO_NUM_6
#define CG_PIN_HUB75_R2 GPIO_NUM_7
#define CG_PIN_HUB75_G2 GPIO_NUM_15
#define CG_PIN_HUB75_B2 GPIO_NUM_16
#define CG_PIN_HUB75_A GPIO_NUM_17
#define CG_PIN_HUB75_B GPIO_NUM_18
#define CG_PIN_HUB75_C GPIO_NUM_8
#define CG_PIN_HUB75_D GPIO_NUM_9
#define CG_PIN_HUB75_E GPIO_NUM_10
#define CG_PIN_HUB75_LAT GPIO_NUM_11
#define CG_PIN_HUB75_CLK GPIO_NUM_12
#define CG_PIN_HUB75_OE GPIO_NUM_13

#define CG_PIN_BOOT GPIO_NUM_0
#define CG_PIN_RESERVED_JTAG_BOOT GPIO_NUM_3
#define CG_PIN_RESERVED_RGB_LED GPIO_NUM_38
#define CG_PIN_RESERVED_USB_D_MINUS GPIO_NUM_19
#define CG_PIN_RESERVED_USB_D_PLUS GPIO_NUM_20
#define CG_PIN_RESERVED_UART0_TX GPIO_NUM_43
#define CG_PIN_RESERVED_UART0_RX GPIO_NUM_44
#define CG_PIN_RESERVED_BOOT_45 GPIO_NUM_45
#define CG_PIN_RESERVED_BOOT_46 GPIO_NUM_46

#define CG_ADDR_MLX90640 0x33U
#define CG_ADDR_SCD41 0x62U
#define CG_ADDR_SHT35_A 0x44U
#define CG_ADDR_SHT35_B 0x45U

#ifdef __cplusplus
}
#endif
